function handleException(errorMessage: string): never {
    throw new Error(errorMessage)
}

// handleException("test error")

